/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MainRouteImport } from './routes/_main'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MainSettingsRouteImport } from './routes/_main/settings'
import { Route as MainAgentsIndexRouteImport } from './routes/_main/agents.index'
import { Route as MainAgentsAgentNameRouteImport } from './routes/_main/agents.$agentName'
import { Route as MainAgentsCreateRouteImport } from './routes/_main/agents.create'
import { Route as MainAiProvidersIndexRouteImport } from './routes/_main/ai-providers.index'
import { Route as MainAiProvidersCreateRouteImport } from './routes/_main/ai-providers.create'
import { Route as MainAgentsAgentNameIndexRouteImport } from './routes/_main/agents.$agentName.index'
import { Route as MainAgentsAgentNameEditRouteImport } from './routes/_main/agents.$agentName.edit'
import { Route as MainAgentsAgentNameLogsRouteImport } from './routes/_main/agents.$agentName.logs'
import { Route as MainAiProvidersIdAddModelsRouteImport } from './routes/_main/ai-providers.$id.add-models'
import { Route as MainAiProvidersIdEditRouteImport } from './routes/_main/ai-providers.$id.edit'
import { Route as MainAgentsAgentNameLogsIndexRouteImport } from './routes/_main/agents.$agentName.logs.index'
import { Route as MainAgentsAgentNameLogsLogIdRouteImport } from './routes/_main/agents.$agentName.logs.$logId'
import { Route as MainAgentsAgentNameSkillsIndexRouteImport } from './routes/_main/agents.$agentName.skills.index'
import { Route as MainAgentsAgentNameSkillsSkillNameRouteImport } from './routes/_main/agents.$agentName.skills.$skillName'
import { Route as MainAgentsAgentNameSkillsCreateRouteImport } from './routes/_main/agents.$agentName.skills.create'
import { Route as MainAgentsAgentNameSkillsSkillNameIndexRouteImport } from './routes/_main/agents.$agentName.skills.$skillName.index'
import { Route as MainAgentsAgentNameSkillsSkillNameEditRouteImport } from './routes/_main/agents.$agentName.skills.$skillName.edit'
import { Route as MainAgentsAgentNameSkillsSkillNameEvaluationsRouteImport } from './routes/_main/agents.$agentName.skills.$skillName.evaluations'
import { Route as MainAgentsAgentNameSkillsSkillNameEventsRouteImport } from './routes/_main/agents.$agentName.skills.$skillName.events'
import { Route as MainAgentsAgentNameSkillsSkillNameLogsRouteImport } from './routes/_main/agents.$agentName.skills.$skillName.logs'
import { Route as MainAgentsAgentNameSkillsSkillNameSetupRouteImport } from './routes/_main/agents.$agentName.skills.$skillName.setup'
import { Route as MainAgentsAgentNameSkillsSkillNameClustersIndexRouteImport } from './routes/_main/agents.$agentName.skills.$skillName.clusters.index'
import { Route as MainAgentsAgentNameSkillsSkillNameClustersClusterIdRouteImport } from './routes/_main/agents.$agentName.skills.$skillName.clusters.$clusterId'
import { Route as MainAgentsAgentNameSkillsSkillNameEvaluationsIndexRouteImport } from './routes/_main/agents.$agentName.skills.$skillName.evaluations.index'
import { Route as MainAgentsAgentNameSkillsSkillNameLogsIndexRouteImport } from './routes/_main/agents.$agentName.skills.$skillName.logs.index'
import { Route as MainAgentsAgentNameSkillsSkillNameLogsLogIdRouteImport } from './routes/_main/agents.$agentName.skills.$skillName.logs.$logId'
import { Route as MainAgentsAgentNameSkillsSkillNameClustersClusterIdConfigurationsRouteImport } from './routes/_main/agents.$agentName.skills.$skillName.clusters.$clusterId.configurations'
import { Route as MainAgentsAgentNameSkillsSkillNameEvaluationsEvaluationIdEditRouteImport } from './routes/_main/agents.$agentName.skills.$skillName.evaluations.$evaluationId.edit'
import { Route as MainAgentsAgentNameSkillsSkillNameClustersClusterIdConfigurationsIndexRouteImport } from './routes/_main/agents.$agentName.skills.$skillName.clusters.$clusterId.configurations.index'
import { Route as MainAgentsAgentNameSkillsSkillNameClustersClusterIdConfigurationsArmIdRouteImport } from './routes/_main/agents.$agentName.skills.$skillName.clusters.$clusterId.configurations.$armId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))
const MainSettingsRoute = MainSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MainRoute,
} as any).lazy(() =>
  import('./routes/_main/settings.lazy').then((d) => d.Route),
)
const MainAgentsIndexRoute = MainAgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => MainRoute,
} as any).lazy(() =>
  import('./routes/_main/agents.index.lazy').then((d) => d.Route),
)
const MainAgentsAgentNameRoute = MainAgentsAgentNameRouteImport.update({
  id: '/agents/$agentName',
  path: '/agents/$agentName',
  getParentRoute: () => MainRoute,
} as any)
const MainAgentsCreateRoute = MainAgentsCreateRouteImport.update({
  id: '/agents/create',
  path: '/agents/create',
  getParentRoute: () => MainRoute,
} as any).lazy(() =>
  import('./routes/_main/agents.create.lazy').then((d) => d.Route),
)
const MainAiProvidersIndexRoute = MainAiProvidersIndexRouteImport.update({
  id: '/ai-providers/',
  path: '/ai-providers/',
  getParentRoute: () => MainRoute,
} as any).lazy(() =>
  import('./routes/_main/ai-providers.index.lazy').then((d) => d.Route),
)
const MainAiProvidersCreateRoute = MainAiProvidersCreateRouteImport.update({
  id: '/ai-providers/create',
  path: '/ai-providers/create',
  getParentRoute: () => MainRoute,
} as any).lazy(() =>
  import('./routes/_main/ai-providers.create.lazy').then((d) => d.Route),
)
const MainAgentsAgentNameIndexRoute =
  MainAgentsAgentNameIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => MainAgentsAgentNameRoute,
  } as any).lazy(() =>
    import('./routes/_main/agents.$agentName.index.lazy').then((d) => d.Route),
  )
const MainAgentsAgentNameEditRoute = MainAgentsAgentNameEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => MainAgentsAgentNameRoute,
} as any).lazy(() =>
  import('./routes/_main/agents.$agentName.edit.lazy').then((d) => d.Route),
)
const MainAgentsAgentNameLogsRoute = MainAgentsAgentNameLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => MainAgentsAgentNameRoute,
} as any)
const MainAiProvidersIdAddModelsRoute =
  MainAiProvidersIdAddModelsRouteImport.update({
    id: '/ai-providers/$id/add-models',
    path: '/ai-providers/$id/add-models',
    getParentRoute: () => MainRoute,
  } as any).lazy(() =>
    import('./routes/_main/ai-providers.$id.add-models.lazy').then(
      (d) => d.Route,
    ),
  )
const MainAiProvidersIdEditRoute = MainAiProvidersIdEditRouteImport.update({
  id: '/ai-providers/$id/edit',
  path: '/ai-providers/$id/edit',
  getParentRoute: () => MainRoute,
} as any).lazy(() =>
  import('./routes/_main/ai-providers.$id.edit.lazy').then((d) => d.Route),
)
const MainAgentsAgentNameLogsIndexRoute =
  MainAgentsAgentNameLogsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => MainAgentsAgentNameLogsRoute,
  } as any).lazy(() =>
    import('./routes/_main/agents.$agentName.logs.index.lazy').then(
      (d) => d.Route,
    ),
  )
const MainAgentsAgentNameLogsLogIdRoute =
  MainAgentsAgentNameLogsLogIdRouteImport.update({
    id: '/$logId',
    path: '/$logId',
    getParentRoute: () => MainAgentsAgentNameLogsRoute,
  } as any).lazy(() =>
    import('./routes/_main/agents.$agentName.logs.$logId.lazy').then(
      (d) => d.Route,
    ),
  )
const MainAgentsAgentNameSkillsIndexRoute =
  MainAgentsAgentNameSkillsIndexRouteImport.update({
    id: '/skills/',
    path: '/skills/',
    getParentRoute: () => MainAgentsAgentNameRoute,
  } as any).lazy(() =>
    import('./routes/_main/agents.$agentName.skills.index.lazy').then(
      (d) => d.Route,
    ),
  )
const MainAgentsAgentNameSkillsSkillNameRoute =
  MainAgentsAgentNameSkillsSkillNameRouteImport.update({
    id: '/skills/$skillName',
    path: '/skills/$skillName',
    getParentRoute: () => MainAgentsAgentNameRoute,
  } as any)
const MainAgentsAgentNameSkillsCreateRoute =
  MainAgentsAgentNameSkillsCreateRouteImport.update({
    id: '/skills/create',
    path: '/skills/create',
    getParentRoute: () => MainAgentsAgentNameRoute,
  } as any).lazy(() =>
    import('./routes/_main/agents.$agentName.skills.create.lazy').then(
      (d) => d.Route,
    ),
  )
const MainAgentsAgentNameSkillsSkillNameIndexRoute =
  MainAgentsAgentNameSkillsSkillNameIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => MainAgentsAgentNameSkillsSkillNameRoute,
  } as any).lazy(() =>
    import('./routes/_main/agents.$agentName.skills.$skillName.index.lazy').then(
      (d) => d.Route,
    ),
  )
const MainAgentsAgentNameSkillsSkillNameEditRoute =
  MainAgentsAgentNameSkillsSkillNameEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => MainAgentsAgentNameSkillsSkillNameRoute,
  } as any).lazy(() =>
    import('./routes/_main/agents.$agentName.skills.$skillName.edit.lazy').then(
      (d) => d.Route,
    ),
  )
const MainAgentsAgentNameSkillsSkillNameEvaluationsRoute =
  MainAgentsAgentNameSkillsSkillNameEvaluationsRouteImport.update({
    id: '/evaluations',
    path: '/evaluations',
    getParentRoute: () => MainAgentsAgentNameSkillsSkillNameRoute,
  } as any)
const MainAgentsAgentNameSkillsSkillNameEventsRoute =
  MainAgentsAgentNameSkillsSkillNameEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => MainAgentsAgentNameSkillsSkillNameRoute,
  } as any).lazy(() =>
    import('./routes/_main/agents.$agentName.skills.$skillName.events.lazy').then(
      (d) => d.Route,
    ),
  )
const MainAgentsAgentNameSkillsSkillNameLogsRoute =
  MainAgentsAgentNameSkillsSkillNameLogsRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => MainAgentsAgentNameSkillsSkillNameRoute,
  } as any)
const MainAgentsAgentNameSkillsSkillNameSetupRoute =
  MainAgentsAgentNameSkillsSkillNameSetupRouteImport.update({
    id: '/setup',
    path: '/setup',
    getParentRoute: () => MainAgentsAgentNameSkillsSkillNameRoute,
  } as any).lazy(() =>
    import('./routes/_main/agents.$agentName.skills.$skillName.setup.lazy').then(
      (d) => d.Route,
    ),
  )
const MainAgentsAgentNameSkillsSkillNameClustersIndexRoute =
  MainAgentsAgentNameSkillsSkillNameClustersIndexRouteImport.update({
    id: '/clusters/',
    path: '/clusters/',
    getParentRoute: () => MainAgentsAgentNameSkillsSkillNameRoute,
  } as any)
const MainAgentsAgentNameSkillsSkillNameClustersClusterIdRoute =
  MainAgentsAgentNameSkillsSkillNameClustersClusterIdRouteImport.update({
    id: '/clusters/$clusterId',
    path: '/clusters/$clusterId',
    getParentRoute: () => MainAgentsAgentNameSkillsSkillNameRoute,
  } as any)
const MainAgentsAgentNameSkillsSkillNameEvaluationsIndexRoute =
  MainAgentsAgentNameSkillsSkillNameEvaluationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => MainAgentsAgentNameSkillsSkillNameEvaluationsRoute,
  } as any).lazy(() =>
    import('./routes/_main/agents.$agentName.skills.$skillName.evaluations.index.lazy').then(
      (d) => d.Route,
    ),
  )
const MainAgentsAgentNameSkillsSkillNameLogsIndexRoute =
  MainAgentsAgentNameSkillsSkillNameLogsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => MainAgentsAgentNameSkillsSkillNameLogsRoute,
  } as any)
const MainAgentsAgentNameSkillsSkillNameLogsLogIdRoute =
  MainAgentsAgentNameSkillsSkillNameLogsLogIdRouteImport.update({
    id: '/$logId',
    path: '/$logId',
    getParentRoute: () => MainAgentsAgentNameSkillsSkillNameLogsRoute,
  } as any)
const MainAgentsAgentNameSkillsSkillNameClustersClusterIdConfigurationsRoute =
  MainAgentsAgentNameSkillsSkillNameClustersClusterIdConfigurationsRouteImport.update(
    {
      id: '/configurations',
      path: '/configurations',
      getParentRoute: () =>
        MainAgentsAgentNameSkillsSkillNameClustersClusterIdRoute,
    } as any,
  )
const MainAgentsAgentNameSkillsSkillNameEvaluationsEvaluationIdEditRoute =
  MainAgentsAgentNameSkillsSkillNameEvaluationsEvaluationIdEditRouteImport.update(
    {
      id: '/$evaluationId/edit',
      path: '/$evaluationId/edit',
      getParentRoute: () => MainAgentsAgentNameSkillsSkillNameEvaluationsRoute,
    } as any,
  ).lazy(() =>
    import('./routes/_main/agents.$agentName.skills.$skillName.evaluations.$evaluationId.edit.lazy').then(
      (d) => d.Route,
    ),
  )
const MainAgentsAgentNameSkillsSkillNameClustersClusterIdConfigurationsIndexRoute =
  MainAgentsAgentNameSkillsSkillNameClustersClusterIdConfigurationsIndexRouteImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        MainAgentsAgentNameSkillsSkillNameClustersClusterIdConfigurationsRoute,
    } as any,
  ).lazy(() =>
    import('./routes/_main/agents.$agentName.skills.$skillName.clusters.$clusterId.configurations.index.lazy').then(
      (d) => d.Route,
    ),
  )
const MainAgentsAgentNameSkillsSkillNameClustersClusterIdConfigurationsArmIdRoute =
  MainAgentsAgentNameSkillsSkillNameClustersClusterIdConfigurationsArmIdRouteImport.update(
    {
      id: '/$armId',
      path: '/$armId',
      getParentRoute: () =>
        MainAgentsAgentNameSkillsSkillNameClustersClusterIdConfigurationsRoute,
    } as any,
  ).lazy(() =>
    import('./routes/_main/agents.$agentName.skills.$skillName.clusters.$clusterId.configurations.$armId.lazy').then(
      (d) => d.Route,
    ),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof MainSettingsRoute
  '/agents/$agentName': typeof MainAgentsAgentNameRouteWithChildren
  '/agents/create': typeof MainAgentsCreateRoute
  '/ai-providers/create': typeof MainAiProvidersCreateRoute
  '/agents/': typeof MainAgentsIndexRoute
  '/ai-providers/': typeof MainAiProvidersIndexRoute
  '/agents/$agentName/edit': typeof MainAgentsAgentNameEditRoute
  '/agents/$agentName/logs': typeof MainAgentsAgentNameLogsRouteWithChildren
  '/ai-providers/$id/add-models': typeof MainAiProvidersIdAddModelsRoute
  '/ai-providers/$id/edit': typeof MainAiProvidersIdEditRoute
  '/agents/$agentName/': typeof MainAgentsAgentNameIndexRoute
  '/agents/$agentName/logs/$logId': typeof MainAgentsAgentNameLogsLogIdRoute
  '/agents/$agentName/skills/$skillName': typeof MainAgentsAgentNameSkillsSkillNameRouteWithChildren
  '/agents/$agentName/skills/create': typeof MainAgentsAgentNameSkillsCreateRoute
  '/agents/$agentName/logs/': typeof MainAgentsAgentNameLogsIndexRoute
  '/agents/$agentName/skills/': typeof MainAgentsAgentNameSkillsIndexRoute
  '/agents/$agentName/skills/$skillName/edit': typeof MainAgentsAgentNameSkillsSkillNameEditRoute
  '/agents/$agentName/skills/$skillName/evaluations': typeof MainAgentsAgentNameSkillsSkillNameEvaluationsRouteWithChildren
  '/agents/$agentName/skills/$skillName/events': typeof MainAgentsAgentNameSkillsSkillNameEventsRoute
  '/agents/$agentName/skills/$skillName/logs': typeof MainAgentsAgentNameSkillsSkillNameLogsRouteWithChildren
  '/agents/$agentName/skills/$skillName/setup': typeof MainAgentsAgentNameSkillsSkillNameSetupRoute
  '/agents/$agentName/skills/$skillName/': typeof MainAgentsAgentNameSkillsSkillNameIndexRoute
  '/agents/$agentName/skills/$skillName/clusters/$clusterId': typeof MainAgentsAgentNameSkillsSkillNameClustersClusterIdRouteWithChildren
  '/agents/$agentName/skills/$skillName/logs/$logId': typeof MainAgentsAgentNameSkillsSkillNameLogsLogIdRoute
  '/agents/$agentName/skills/$skillName/clusters/': typeof MainAgentsAgentNameSkillsSkillNameClustersIndexRoute
  '/agents/$agentName/skills/$skillName/evaluations/': typeof MainAgentsAgentNameSkillsSkillNameEvaluationsIndexRoute
  '/agents/$agentName/skills/$skillName/logs/': typeof MainAgentsAgentNameSkillsSkillNameLogsIndexRoute
  '/agents/$agentName/skills/$skillName/clusters/$clusterId/configurations': typeof MainAgentsAgentNameSkillsSkillNameClustersClusterIdConfigurationsRouteWithChildren
  '/agents/$agentName/skills/$skillName/evaluations/$evaluationId/edit': typeof MainAgentsAgentNameSkillsSkillNameEvaluationsEvaluationIdEditRoute
  '/agents/$agentName/skills/$skillName/clusters/$clusterId/configurations/$armId': typeof MainAgentsAgentNameSkillsSkillNameClustersClusterIdConfigurationsArmIdRoute
  '/agents/$agentName/skills/$skillName/clusters/$clusterId/configurations/': typeof MainAgentsAgentNameSkillsSkillNameClustersClusterIdConfigurationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof MainSettingsRoute
  '/agents/create': typeof MainAgentsCreateRoute
  '/ai-providers/create': typeof MainAiProvidersCreateRoute
  '/agents': typeof MainAgentsIndexRoute
  '/ai-providers': typeof MainAiProvidersIndexRoute
  '/agents/$agentName/edit': typeof MainAgentsAgentNameEditRoute
  '/ai-providers/$id/add-models': typeof MainAiProvidersIdAddModelsRoute
  '/ai-providers/$id/edit': typeof MainAiProvidersIdEditRoute
  '/agents/$agentName': typeof MainAgentsAgentNameIndexRoute
  '/agents/$agentName/logs/$logId': typeof MainAgentsAgentNameLogsLogIdRoute
  '/agents/$agentName/skills/create': typeof MainAgentsAgentNameSkillsCreateRoute
  '/agents/$agentName/logs': typeof MainAgentsAgentNameLogsIndexRoute
  '/agents/$agentName/skills': typeof MainAgentsAgentNameSkillsIndexRoute
  '/agents/$agentName/skills/$skillName/edit': typeof MainAgentsAgentNameSkillsSkillNameEditRoute
  '/agents/$agentName/skills/$skillName/events': typeof MainAgentsAgentNameSkillsSkillNameEventsRoute
  '/agents/$agentName/skills/$skillName/setup': typeof MainAgentsAgentNameSkillsSkillNameSetupRoute
  '/agents/$agentName/skills/$skillName': typeof MainAgentsAgentNameSkillsSkillNameIndexRoute
  '/agents/$agentName/skills/$skillName/clusters/$clusterId': typeof MainAgentsAgentNameSkillsSkillNameClustersClusterIdRouteWithChildren
  '/agents/$agentName/skills/$skillName/logs/$logId': typeof MainAgentsAgentNameSkillsSkillNameLogsLogIdRoute
  '/agents/$agentName/skills/$skillName/clusters': typeof MainAgentsAgentNameSkillsSkillNameClustersIndexRoute
  '/agents/$agentName/skills/$skillName/evaluations': typeof MainAgentsAgentNameSkillsSkillNameEvaluationsIndexRoute
  '/agents/$agentName/skills/$skillName/logs': typeof MainAgentsAgentNameSkillsSkillNameLogsIndexRoute
  '/agents/$agentName/skills/$skillName/evaluations/$evaluationId/edit': typeof MainAgentsAgentNameSkillsSkillNameEvaluationsEvaluationIdEditRoute
  '/agents/$agentName/skills/$skillName/clusters/$clusterId/configurations/$armId': typeof MainAgentsAgentNameSkillsSkillNameClustersClusterIdConfigurationsArmIdRoute
  '/agents/$agentName/skills/$skillName/clusters/$clusterId/configurations': typeof MainAgentsAgentNameSkillsSkillNameClustersClusterIdConfigurationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_main': typeof MainRouteWithChildren
  '/login': typeof LoginRoute
  '/_main/settings': typeof MainSettingsRoute
  '/_main/agents/$agentName': typeof MainAgentsAgentNameRouteWithChildren
  '/_main/agents/create': typeof MainAgentsCreateRoute
  '/_main/ai-providers/create': typeof MainAiProvidersCreateRoute
  '/_main/agents/': typeof MainAgentsIndexRoute
  '/_main/ai-providers/': typeof MainAiProvidersIndexRoute
  '/_main/agents/$agentName/edit': typeof MainAgentsAgentNameEditRoute
  '/_main/agents/$agentName/logs': typeof MainAgentsAgentNameLogsRouteWithChildren
  '/_main/ai-providers/$id/add-models': typeof MainAiProvidersIdAddModelsRoute
  '/_main/ai-providers/$id/edit': typeof MainAiProvidersIdEditRoute
  '/_main/agents/$agentName/': typeof MainAgentsAgentNameIndexRoute
  '/_main/agents/$agentName/logs/$logId': typeof MainAgentsAgentNameLogsLogIdRoute
  '/_main/agents/$agentName/skills/$skillName': typeof MainAgentsAgentNameSkillsSkillNameRouteWithChildren
  '/_main/agents/$agentName/skills/create': typeof MainAgentsAgentNameSkillsCreateRoute
  '/_main/agents/$agentName/logs/': typeof MainAgentsAgentNameLogsIndexRoute
  '/_main/agents/$agentName/skills/': typeof MainAgentsAgentNameSkillsIndexRoute
  '/_main/agents/$agentName/skills/$skillName/edit': typeof MainAgentsAgentNameSkillsSkillNameEditRoute
  '/_main/agents/$agentName/skills/$skillName/evaluations': typeof MainAgentsAgentNameSkillsSkillNameEvaluationsRouteWithChildren
  '/_main/agents/$agentName/skills/$skillName/events': typeof MainAgentsAgentNameSkillsSkillNameEventsRoute
  '/_main/agents/$agentName/skills/$skillName/logs': typeof MainAgentsAgentNameSkillsSkillNameLogsRouteWithChildren
  '/_main/agents/$agentName/skills/$skillName/setup': typeof MainAgentsAgentNameSkillsSkillNameSetupRoute
  '/_main/agents/$agentName/skills/$skillName/': typeof MainAgentsAgentNameSkillsSkillNameIndexRoute
  '/_main/agents/$agentName/skills/$skillName/clusters/$clusterId': typeof MainAgentsAgentNameSkillsSkillNameClustersClusterIdRouteWithChildren
  '/_main/agents/$agentName/skills/$skillName/logs/$logId': typeof MainAgentsAgentNameSkillsSkillNameLogsLogIdRoute
  '/_main/agents/$agentName/skills/$skillName/clusters/': typeof MainAgentsAgentNameSkillsSkillNameClustersIndexRoute
  '/_main/agents/$agentName/skills/$skillName/evaluations/': typeof MainAgentsAgentNameSkillsSkillNameEvaluationsIndexRoute
  '/_main/agents/$agentName/skills/$skillName/logs/': typeof MainAgentsAgentNameSkillsSkillNameLogsIndexRoute
  '/_main/agents/$agentName/skills/$skillName/clusters/$clusterId/configurations': typeof MainAgentsAgentNameSkillsSkillNameClustersClusterIdConfigurationsRouteWithChildren
  '/_main/agents/$agentName/skills/$skillName/evaluations/$evaluationId/edit': typeof MainAgentsAgentNameSkillsSkillNameEvaluationsEvaluationIdEditRoute
  '/_main/agents/$agentName/skills/$skillName/clusters/$clusterId/configurations/$armId': typeof MainAgentsAgentNameSkillsSkillNameClustersClusterIdConfigurationsArmIdRoute
  '/_main/agents/$agentName/skills/$skillName/clusters/$clusterId/configurations/': typeof MainAgentsAgentNameSkillsSkillNameClustersClusterIdConfigurationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/settings'
    | '/agents/$agentName'
    | '/agents/create'
    | '/ai-providers/create'
    | '/agents/'
    | '/ai-providers/'
    | '/agents/$agentName/edit'
    | '/agents/$agentName/logs'
    | '/ai-providers/$id/add-models'
    | '/ai-providers/$id/edit'
    | '/agents/$agentName/'
    | '/agents/$agentName/logs/$logId'
    | '/agents/$agentName/skills/$skillName'
    | '/agents/$agentName/skills/create'
    | '/agents/$agentName/logs/'
    | '/agents/$agentName/skills/'
    | '/agents/$agentName/skills/$skillName/edit'
    | '/agents/$agentName/skills/$skillName/evaluations'
    | '/agents/$agentName/skills/$skillName/events'
    | '/agents/$agentName/skills/$skillName/logs'
    | '/agents/$agentName/skills/$skillName/setup'
    | '/agents/$agentName/skills/$skillName/'
    | '/agents/$agentName/skills/$skillName/clusters/$clusterId'
    | '/agents/$agentName/skills/$skillName/logs/$logId'
    | '/agents/$agentName/skills/$skillName/clusters/'
    | '/agents/$agentName/skills/$skillName/evaluations/'
    | '/agents/$agentName/skills/$skillName/logs/'
    | '/agents/$agentName/skills/$skillName/clusters/$clusterId/configurations'
    | '/agents/$agentName/skills/$skillName/evaluations/$evaluationId/edit'
    | '/agents/$agentName/skills/$skillName/clusters/$clusterId/configurations/$armId'
    | '/agents/$agentName/skills/$skillName/clusters/$clusterId/configurations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/settings'
    | '/agents/create'
    | '/ai-providers/create'
    | '/agents'
    | '/ai-providers'
    | '/agents/$agentName/edit'
    | '/ai-providers/$id/add-models'
    | '/ai-providers/$id/edit'
    | '/agents/$agentName'
    | '/agents/$agentName/logs/$logId'
    | '/agents/$agentName/skills/create'
    | '/agents/$agentName/logs'
    | '/agents/$agentName/skills'
    | '/agents/$agentName/skills/$skillName/edit'
    | '/agents/$agentName/skills/$skillName/events'
    | '/agents/$agentName/skills/$skillName/setup'
    | '/agents/$agentName/skills/$skillName'
    | '/agents/$agentName/skills/$skillName/clusters/$clusterId'
    | '/agents/$agentName/skills/$skillName/logs/$logId'
    | '/agents/$agentName/skills/$skillName/clusters'
    | '/agents/$agentName/skills/$skillName/evaluations'
    | '/agents/$agentName/skills/$skillName/logs'
    | '/agents/$agentName/skills/$skillName/evaluations/$evaluationId/edit'
    | '/agents/$agentName/skills/$skillName/clusters/$clusterId/configurations/$armId'
    | '/agents/$agentName/skills/$skillName/clusters/$clusterId/configurations'
  id:
    | '__root__'
    | '/'
    | '/_main'
    | '/login'
    | '/_main/settings'
    | '/_main/agents/$agentName'
    | '/_main/agents/create'
    | '/_main/ai-providers/create'
    | '/_main/agents/'
    | '/_main/ai-providers/'
    | '/_main/agents/$agentName/edit'
    | '/_main/agents/$agentName/logs'
    | '/_main/ai-providers/$id/add-models'
    | '/_main/ai-providers/$id/edit'
    | '/_main/agents/$agentName/'
    | '/_main/agents/$agentName/logs/$logId'
    | '/_main/agents/$agentName/skills/$skillName'
    | '/_main/agents/$agentName/skills/create'
    | '/_main/agents/$agentName/logs/'
    | '/_main/agents/$agentName/skills/'
    | '/_main/agents/$agentName/skills/$skillName/edit'
    | '/_main/agents/$agentName/skills/$skillName/evaluations'
    | '/_main/agents/$agentName/skills/$skillName/events'
    | '/_main/agents/$agentName/skills/$skillName/logs'
    | '/_main/agents/$agentName/skills/$skillName/setup'
    | '/_main/agents/$agentName/skills/$skillName/'
    | '/_main/agents/$agentName/skills/$skillName/clusters/$clusterId'
    | '/_main/agents/$agentName/skills/$skillName/logs/$logId'
    | '/_main/agents/$agentName/skills/$skillName/clusters/'
    | '/_main/agents/$agentName/skills/$skillName/evaluations/'
    | '/_main/agents/$agentName/skills/$skillName/logs/'
    | '/_main/agents/$agentName/skills/$skillName/clusters/$clusterId/configurations'
    | '/_main/agents/$agentName/skills/$skillName/evaluations/$evaluationId/edit'
    | '/_main/agents/$agentName/skills/$skillName/clusters/$clusterId/configurations/$armId'
    | '/_main/agents/$agentName/skills/$skillName/clusters/$clusterId/configurations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MainRoute: typeof MainRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/settings': {
      id: '/_main/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof MainSettingsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/agents/': {
      id: '/_main/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof MainAgentsIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/agents/$agentName': {
      id: '/_main/agents/$agentName'
      path: '/agents/$agentName'
      fullPath: '/agents/$agentName'
      preLoaderRoute: typeof MainAgentsAgentNameRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/agents/create': {
      id: '/_main/agents/create'
      path: '/agents/create'
      fullPath: '/agents/create'
      preLoaderRoute: typeof MainAgentsCreateRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/ai-providers/': {
      id: '/_main/ai-providers/'
      path: '/ai-providers'
      fullPath: '/ai-providers/'
      preLoaderRoute: typeof MainAiProvidersIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/ai-providers/create': {
      id: '/_main/ai-providers/create'
      path: '/ai-providers/create'
      fullPath: '/ai-providers/create'
      preLoaderRoute: typeof MainAiProvidersCreateRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/agents/$agentName/': {
      id: '/_main/agents/$agentName/'
      path: '/'
      fullPath: '/agents/$agentName/'
      preLoaderRoute: typeof MainAgentsAgentNameIndexRouteImport
      parentRoute: typeof MainAgentsAgentNameRoute
    }
    '/_main/agents/$agentName/edit': {
      id: '/_main/agents/$agentName/edit'
      path: '/edit'
      fullPath: '/agents/$agentName/edit'
      preLoaderRoute: typeof MainAgentsAgentNameEditRouteImport
      parentRoute: typeof MainAgentsAgentNameRoute
    }
    '/_main/agents/$agentName/logs': {
      id: '/_main/agents/$agentName/logs'
      path: '/logs'
      fullPath: '/agents/$agentName/logs'
      preLoaderRoute: typeof MainAgentsAgentNameLogsRouteImport
      parentRoute: typeof MainAgentsAgentNameRoute
    }
    '/_main/ai-providers/$id/add-models': {
      id: '/_main/ai-providers/$id/add-models'
      path: '/ai-providers/$id/add-models'
      fullPath: '/ai-providers/$id/add-models'
      preLoaderRoute: typeof MainAiProvidersIdAddModelsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/ai-providers/$id/edit': {
      id: '/_main/ai-providers/$id/edit'
      path: '/ai-providers/$id/edit'
      fullPath: '/ai-providers/$id/edit'
      preLoaderRoute: typeof MainAiProvidersIdEditRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/agents/$agentName/logs/': {
      id: '/_main/agents/$agentName/logs/'
      path: '/'
      fullPath: '/agents/$agentName/logs/'
      preLoaderRoute: typeof MainAgentsAgentNameLogsIndexRouteImport
      parentRoute: typeof MainAgentsAgentNameLogsRoute
    }
    '/_main/agents/$agentName/logs/$logId': {
      id: '/_main/agents/$agentName/logs/$logId'
      path: '/$logId'
      fullPath: '/agents/$agentName/logs/$logId'
      preLoaderRoute: typeof MainAgentsAgentNameLogsLogIdRouteImport
      parentRoute: typeof MainAgentsAgentNameLogsRoute
    }
    '/_main/agents/$agentName/skills/': {
      id: '/_main/agents/$agentName/skills/'
      path: '/skills'
      fullPath: '/agents/$agentName/skills/'
      preLoaderRoute: typeof MainAgentsAgentNameSkillsIndexRouteImport
      parentRoute: typeof MainAgentsAgentNameRoute
    }
    '/_main/agents/$agentName/skills/$skillName': {
      id: '/_main/agents/$agentName/skills/$skillName'
      path: '/skills/$skillName'
      fullPath: '/agents/$agentName/skills/$skillName'
      preLoaderRoute: typeof MainAgentsAgentNameSkillsSkillNameRouteImport
      parentRoute: typeof MainAgentsAgentNameRoute
    }
    '/_main/agents/$agentName/skills/create': {
      id: '/_main/agents/$agentName/skills/create'
      path: '/skills/create'
      fullPath: '/agents/$agentName/skills/create'
      preLoaderRoute: typeof MainAgentsAgentNameSkillsCreateRouteImport
      parentRoute: typeof MainAgentsAgentNameRoute
    }
    '/_main/agents/$agentName/skills/$skillName/': {
      id: '/_main/agents/$agentName/skills/$skillName/'
      path: '/'
      fullPath: '/agents/$agentName/skills/$skillName/'
      preLoaderRoute: typeof MainAgentsAgentNameSkillsSkillNameIndexRouteImport
      parentRoute: typeof MainAgentsAgentNameSkillsSkillNameRoute
    }
    '/_main/agents/$agentName/skills/$skillName/edit': {
      id: '/_main/agents/$agentName/skills/$skillName/edit'
      path: '/edit'
      fullPath: '/agents/$agentName/skills/$skillName/edit'
      preLoaderRoute: typeof MainAgentsAgentNameSkillsSkillNameEditRouteImport
      parentRoute: typeof MainAgentsAgentNameSkillsSkillNameRoute
    }
    '/_main/agents/$agentName/skills/$skillName/evaluations': {
      id: '/_main/agents/$agentName/skills/$skillName/evaluations'
      path: '/evaluations'
      fullPath: '/agents/$agentName/skills/$skillName/evaluations'
      preLoaderRoute: typeof MainAgentsAgentNameSkillsSkillNameEvaluationsRouteImport
      parentRoute: typeof MainAgentsAgentNameSkillsSkillNameRoute
    }
    '/_main/agents/$agentName/skills/$skillName/events': {
      id: '/_main/agents/$agentName/skills/$skillName/events'
      path: '/events'
      fullPath: '/agents/$agentName/skills/$skillName/events'
      preLoaderRoute: typeof MainAgentsAgentNameSkillsSkillNameEventsRouteImport
      parentRoute: typeof MainAgentsAgentNameSkillsSkillNameRoute
    }
    '/_main/agents/$agentName/skills/$skillName/logs': {
      id: '/_main/agents/$agentName/skills/$skillName/logs'
      path: '/logs'
      fullPath: '/agents/$agentName/skills/$skillName/logs'
      preLoaderRoute: typeof MainAgentsAgentNameSkillsSkillNameLogsRouteImport
      parentRoute: typeof MainAgentsAgentNameSkillsSkillNameRoute
    }
    '/_main/agents/$agentName/skills/$skillName/setup': {
      id: '/_main/agents/$agentName/skills/$skillName/setup'
      path: '/setup'
      fullPath: '/agents/$agentName/skills/$skillName/setup'
      preLoaderRoute: typeof MainAgentsAgentNameSkillsSkillNameSetupRouteImport
      parentRoute: typeof MainAgentsAgentNameSkillsSkillNameRoute
    }
    '/_main/agents/$agentName/skills/$skillName/clusters/': {
      id: '/_main/agents/$agentName/skills/$skillName/clusters/'
      path: '/clusters'
      fullPath: '/agents/$agentName/skills/$skillName/clusters/'
      preLoaderRoute: typeof MainAgentsAgentNameSkillsSkillNameClustersIndexRouteImport
      parentRoute: typeof MainAgentsAgentNameSkillsSkillNameRoute
    }
    '/_main/agents/$agentName/skills/$skillName/clusters/$clusterId': {
      id: '/_main/agents/$agentName/skills/$skillName/clusters/$clusterId'
      path: '/clusters/$clusterId'
      fullPath: '/agents/$agentName/skills/$skillName/clusters/$clusterId'
      preLoaderRoute: typeof MainAgentsAgentNameSkillsSkillNameClustersClusterIdRouteImport
      parentRoute: typeof MainAgentsAgentNameSkillsSkillNameRoute
    }
    '/_main/agents/$agentName/skills/$skillName/evaluations/': {
      id: '/_main/agents/$agentName/skills/$skillName/evaluations/'
      path: '/'
      fullPath: '/agents/$agentName/skills/$skillName/evaluations/'
      preLoaderRoute: typeof MainAgentsAgentNameSkillsSkillNameEvaluationsIndexRouteImport
      parentRoute: typeof MainAgentsAgentNameSkillsSkillNameEvaluationsRoute
    }
    '/_main/agents/$agentName/skills/$skillName/logs/': {
      id: '/_main/agents/$agentName/skills/$skillName/logs/'
      path: '/'
      fullPath: '/agents/$agentName/skills/$skillName/logs/'
      preLoaderRoute: typeof MainAgentsAgentNameSkillsSkillNameLogsIndexRouteImport
      parentRoute: typeof MainAgentsAgentNameSkillsSkillNameLogsRoute
    }
    '/_main/agents/$agentName/skills/$skillName/logs/$logId': {
      id: '/_main/agents/$agentName/skills/$skillName/logs/$logId'
      path: '/$logId'
      fullPath: '/agents/$agentName/skills/$skillName/logs/$logId'
      preLoaderRoute: typeof MainAgentsAgentNameSkillsSkillNameLogsLogIdRouteImport
      parentRoute: typeof MainAgentsAgentNameSkillsSkillNameLogsRoute
    }
    '/_main/agents/$agentName/skills/$skillName/clusters/$clusterId/configurations': {
      id: '/_main/agents/$agentName/skills/$skillName/clusters/$clusterId/configurations'
      path: '/configurations'
      fullPath: '/agents/$agentName/skills/$skillName/clusters/$clusterId/configurations'
      preLoaderRoute: typeof MainAgentsAgentNameSkillsSkillNameClustersClusterIdConfigurationsRouteImport
      parentRoute: typeof MainAgentsAgentNameSkillsSkillNameClustersClusterIdRoute
    }
    '/_main/agents/$agentName/skills/$skillName/evaluations/$evaluationId/edit': {
      id: '/_main/agents/$agentName/skills/$skillName/evaluations/$evaluationId/edit'
      path: '/$evaluationId/edit'
      fullPath: '/agents/$agentName/skills/$skillName/evaluations/$evaluationId/edit'
      preLoaderRoute: typeof MainAgentsAgentNameSkillsSkillNameEvaluationsEvaluationIdEditRouteImport
      parentRoute: typeof MainAgentsAgentNameSkillsSkillNameEvaluationsRoute
    }
    '/_main/agents/$agentName/skills/$skillName/clusters/$clusterId/configurations/': {
      id: '/_main/agents/$agentName/skills/$skillName/clusters/$clusterId/configurations/'
      path: '/'
      fullPath: '/agents/$agentName/skills/$skillName/clusters/$clusterId/configurations/'
      preLoaderRoute: typeof MainAgentsAgentNameSkillsSkillNameClustersClusterIdConfigurationsIndexRouteImport
      parentRoute: typeof MainAgentsAgentNameSkillsSkillNameClustersClusterIdConfigurationsRoute
    }
    '/_main/agents/$agentName/skills/$skillName/clusters/$clusterId/configurations/$armId': {
      id: '/_main/agents/$agentName/skills/$skillName/clusters/$clusterId/configurations/$armId'
      path: '/$armId'
      fullPath: '/agents/$agentName/skills/$skillName/clusters/$clusterId/configurations/$armId'
      preLoaderRoute: typeof MainAgentsAgentNameSkillsSkillNameClustersClusterIdConfigurationsArmIdRouteImport
      parentRoute: typeof MainAgentsAgentNameSkillsSkillNameClustersClusterIdConfigurationsRoute
    }
  }
}

interface MainAgentsAgentNameLogsRouteChildren {
  MainAgentsAgentNameLogsLogIdRoute: typeof MainAgentsAgentNameLogsLogIdRoute
  MainAgentsAgentNameLogsIndexRoute: typeof MainAgentsAgentNameLogsIndexRoute
}

const MainAgentsAgentNameLogsRouteChildren: MainAgentsAgentNameLogsRouteChildren =
  {
    MainAgentsAgentNameLogsLogIdRoute: MainAgentsAgentNameLogsLogIdRoute,
    MainAgentsAgentNameLogsIndexRoute: MainAgentsAgentNameLogsIndexRoute,
  }

const MainAgentsAgentNameLogsRouteWithChildren =
  MainAgentsAgentNameLogsRoute._addFileChildren(
    MainAgentsAgentNameLogsRouteChildren,
  )

interface MainAgentsAgentNameSkillsSkillNameEvaluationsRouteChildren {
  MainAgentsAgentNameSkillsSkillNameEvaluationsIndexRoute: typeof MainAgentsAgentNameSkillsSkillNameEvaluationsIndexRoute
  MainAgentsAgentNameSkillsSkillNameEvaluationsEvaluationIdEditRoute: typeof MainAgentsAgentNameSkillsSkillNameEvaluationsEvaluationIdEditRoute
}

const MainAgentsAgentNameSkillsSkillNameEvaluationsRouteChildren: MainAgentsAgentNameSkillsSkillNameEvaluationsRouteChildren =
  {
    MainAgentsAgentNameSkillsSkillNameEvaluationsIndexRoute:
      MainAgentsAgentNameSkillsSkillNameEvaluationsIndexRoute,
    MainAgentsAgentNameSkillsSkillNameEvaluationsEvaluationIdEditRoute:
      MainAgentsAgentNameSkillsSkillNameEvaluationsEvaluationIdEditRoute,
  }

const MainAgentsAgentNameSkillsSkillNameEvaluationsRouteWithChildren =
  MainAgentsAgentNameSkillsSkillNameEvaluationsRoute._addFileChildren(
    MainAgentsAgentNameSkillsSkillNameEvaluationsRouteChildren,
  )

interface MainAgentsAgentNameSkillsSkillNameLogsRouteChildren {
  MainAgentsAgentNameSkillsSkillNameLogsLogIdRoute: typeof MainAgentsAgentNameSkillsSkillNameLogsLogIdRoute
  MainAgentsAgentNameSkillsSkillNameLogsIndexRoute: typeof MainAgentsAgentNameSkillsSkillNameLogsIndexRoute
}

const MainAgentsAgentNameSkillsSkillNameLogsRouteChildren: MainAgentsAgentNameSkillsSkillNameLogsRouteChildren =
  {
    MainAgentsAgentNameSkillsSkillNameLogsLogIdRoute:
      MainAgentsAgentNameSkillsSkillNameLogsLogIdRoute,
    MainAgentsAgentNameSkillsSkillNameLogsIndexRoute:
      MainAgentsAgentNameSkillsSkillNameLogsIndexRoute,
  }

const MainAgentsAgentNameSkillsSkillNameLogsRouteWithChildren =
  MainAgentsAgentNameSkillsSkillNameLogsRoute._addFileChildren(
    MainAgentsAgentNameSkillsSkillNameLogsRouteChildren,
  )

interface MainAgentsAgentNameSkillsSkillNameClustersClusterIdConfigurationsRouteChildren {
  MainAgentsAgentNameSkillsSkillNameClustersClusterIdConfigurationsArmIdRoute: typeof MainAgentsAgentNameSkillsSkillNameClustersClusterIdConfigurationsArmIdRoute
  MainAgentsAgentNameSkillsSkillNameClustersClusterIdConfigurationsIndexRoute: typeof MainAgentsAgentNameSkillsSkillNameClustersClusterIdConfigurationsIndexRoute
}

const MainAgentsAgentNameSkillsSkillNameClustersClusterIdConfigurationsRouteChildren: MainAgentsAgentNameSkillsSkillNameClustersClusterIdConfigurationsRouteChildren =
  {
    MainAgentsAgentNameSkillsSkillNameClustersClusterIdConfigurationsArmIdRoute:
      MainAgentsAgentNameSkillsSkillNameClustersClusterIdConfigurationsArmIdRoute,
    MainAgentsAgentNameSkillsSkillNameClustersClusterIdConfigurationsIndexRoute:
      MainAgentsAgentNameSkillsSkillNameClustersClusterIdConfigurationsIndexRoute,
  }

const MainAgentsAgentNameSkillsSkillNameClustersClusterIdConfigurationsRouteWithChildren =
  MainAgentsAgentNameSkillsSkillNameClustersClusterIdConfigurationsRoute._addFileChildren(
    MainAgentsAgentNameSkillsSkillNameClustersClusterIdConfigurationsRouteChildren,
  )

interface MainAgentsAgentNameSkillsSkillNameClustersClusterIdRouteChildren {
  MainAgentsAgentNameSkillsSkillNameClustersClusterIdConfigurationsRoute: typeof MainAgentsAgentNameSkillsSkillNameClustersClusterIdConfigurationsRouteWithChildren
}

const MainAgentsAgentNameSkillsSkillNameClustersClusterIdRouteChildren: MainAgentsAgentNameSkillsSkillNameClustersClusterIdRouteChildren =
  {
    MainAgentsAgentNameSkillsSkillNameClustersClusterIdConfigurationsRoute:
      MainAgentsAgentNameSkillsSkillNameClustersClusterIdConfigurationsRouteWithChildren,
  }

const MainAgentsAgentNameSkillsSkillNameClustersClusterIdRouteWithChildren =
  MainAgentsAgentNameSkillsSkillNameClustersClusterIdRoute._addFileChildren(
    MainAgentsAgentNameSkillsSkillNameClustersClusterIdRouteChildren,
  )

interface MainAgentsAgentNameSkillsSkillNameRouteChildren {
  MainAgentsAgentNameSkillsSkillNameEditRoute: typeof MainAgentsAgentNameSkillsSkillNameEditRoute
  MainAgentsAgentNameSkillsSkillNameEvaluationsRoute: typeof MainAgentsAgentNameSkillsSkillNameEvaluationsRouteWithChildren
  MainAgentsAgentNameSkillsSkillNameEventsRoute: typeof MainAgentsAgentNameSkillsSkillNameEventsRoute
  MainAgentsAgentNameSkillsSkillNameLogsRoute: typeof MainAgentsAgentNameSkillsSkillNameLogsRouteWithChildren
  MainAgentsAgentNameSkillsSkillNameSetupRoute: typeof MainAgentsAgentNameSkillsSkillNameSetupRoute
  MainAgentsAgentNameSkillsSkillNameIndexRoute: typeof MainAgentsAgentNameSkillsSkillNameIndexRoute
  MainAgentsAgentNameSkillsSkillNameClustersClusterIdRoute: typeof MainAgentsAgentNameSkillsSkillNameClustersClusterIdRouteWithChildren
  MainAgentsAgentNameSkillsSkillNameClustersIndexRoute: typeof MainAgentsAgentNameSkillsSkillNameClustersIndexRoute
}

const MainAgentsAgentNameSkillsSkillNameRouteChildren: MainAgentsAgentNameSkillsSkillNameRouteChildren =
  {
    MainAgentsAgentNameSkillsSkillNameEditRoute:
      MainAgentsAgentNameSkillsSkillNameEditRoute,
    MainAgentsAgentNameSkillsSkillNameEvaluationsRoute:
      MainAgentsAgentNameSkillsSkillNameEvaluationsRouteWithChildren,
    MainAgentsAgentNameSkillsSkillNameEventsRoute:
      MainAgentsAgentNameSkillsSkillNameEventsRoute,
    MainAgentsAgentNameSkillsSkillNameLogsRoute:
      MainAgentsAgentNameSkillsSkillNameLogsRouteWithChildren,
    MainAgentsAgentNameSkillsSkillNameSetupRoute:
      MainAgentsAgentNameSkillsSkillNameSetupRoute,
    MainAgentsAgentNameSkillsSkillNameIndexRoute:
      MainAgentsAgentNameSkillsSkillNameIndexRoute,
    MainAgentsAgentNameSkillsSkillNameClustersClusterIdRoute:
      MainAgentsAgentNameSkillsSkillNameClustersClusterIdRouteWithChildren,
    MainAgentsAgentNameSkillsSkillNameClustersIndexRoute:
      MainAgentsAgentNameSkillsSkillNameClustersIndexRoute,
  }

const MainAgentsAgentNameSkillsSkillNameRouteWithChildren =
  MainAgentsAgentNameSkillsSkillNameRoute._addFileChildren(
    MainAgentsAgentNameSkillsSkillNameRouteChildren,
  )

interface MainAgentsAgentNameRouteChildren {
  MainAgentsAgentNameEditRoute: typeof MainAgentsAgentNameEditRoute
  MainAgentsAgentNameLogsRoute: typeof MainAgentsAgentNameLogsRouteWithChildren
  MainAgentsAgentNameIndexRoute: typeof MainAgentsAgentNameIndexRoute
  MainAgentsAgentNameSkillsSkillNameRoute: typeof MainAgentsAgentNameSkillsSkillNameRouteWithChildren
  MainAgentsAgentNameSkillsCreateRoute: typeof MainAgentsAgentNameSkillsCreateRoute
  MainAgentsAgentNameSkillsIndexRoute: typeof MainAgentsAgentNameSkillsIndexRoute
}

const MainAgentsAgentNameRouteChildren: MainAgentsAgentNameRouteChildren = {
  MainAgentsAgentNameEditRoute: MainAgentsAgentNameEditRoute,
  MainAgentsAgentNameLogsRoute: MainAgentsAgentNameLogsRouteWithChildren,
  MainAgentsAgentNameIndexRoute: MainAgentsAgentNameIndexRoute,
  MainAgentsAgentNameSkillsSkillNameRoute:
    MainAgentsAgentNameSkillsSkillNameRouteWithChildren,
  MainAgentsAgentNameSkillsCreateRoute: MainAgentsAgentNameSkillsCreateRoute,
  MainAgentsAgentNameSkillsIndexRoute: MainAgentsAgentNameSkillsIndexRoute,
}

const MainAgentsAgentNameRouteWithChildren =
  MainAgentsAgentNameRoute._addFileChildren(MainAgentsAgentNameRouteChildren)

interface MainRouteChildren {
  MainSettingsRoute: typeof MainSettingsRoute
  MainAgentsAgentNameRoute: typeof MainAgentsAgentNameRouteWithChildren
  MainAgentsCreateRoute: typeof MainAgentsCreateRoute
  MainAiProvidersCreateRoute: typeof MainAiProvidersCreateRoute
  MainAgentsIndexRoute: typeof MainAgentsIndexRoute
  MainAiProvidersIndexRoute: typeof MainAiProvidersIndexRoute
  MainAiProvidersIdAddModelsRoute: typeof MainAiProvidersIdAddModelsRoute
  MainAiProvidersIdEditRoute: typeof MainAiProvidersIdEditRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainSettingsRoute: MainSettingsRoute,
  MainAgentsAgentNameRoute: MainAgentsAgentNameRouteWithChildren,
  MainAgentsCreateRoute: MainAgentsCreateRoute,
  MainAiProvidersCreateRoute: MainAiProvidersCreateRoute,
  MainAgentsIndexRoute: MainAgentsIndexRoute,
  MainAiProvidersIndexRoute: MainAiProvidersIndexRoute,
  MainAiProvidersIdAddModelsRoute: MainAiProvidersIdAddModelsRoute,
  MainAiProvidersIdEditRoute: MainAiProvidersIdEditRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MainRoute: MainRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
